# Generated by Django 5.0.6 on 2025-12-14 14:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Feriado')),
                ('data', models.DateField(unique=True, verbose_name='Data')),
                ('tipo', models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], default='NACIONAL', max_length=10, verbose_name='Tipo')),
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['data'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('MANHA', 'Manhã'), ('TARDE', 'Tarde'), ('NOITE', 'Noite')], max_length=10, unique=True, verbose_name='Nome do Turno')),
                ('horario_entrada', models.TimeField(verbose_name='Horário de Entrada')),
                ('horario_saida', models.TimeField(verbose_name='Horário de Saída')),
                ('minimo_funcionarios', models.IntegerField(help_text='Número mínimo obrigatório de funcionários neste turno', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Mínimo de Funcionários')),
            ],
            options={
                'verbose_name': 'Turno',
                'verbose_name_plural': 'Turnos',
                'ordering': ['horario_entrada'],
            },
        ),
        migrations.CreateModel(
            name='Escala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MinValueValidator(12)], verbose_name='Mês')),
                ('ano', models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)], verbose_name='Ano')),
                ('data_geracao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Geração')),
                ('gerada_com_sucesso', models.BooleanField(default=False, help_text='Indica se a escala foi gerada sem problemas', verbose_name='Gerada com Sucesso')),
                ('observacoes', models.TextField(blank=True, help_text='Alertas ou problemas encontrados durante a geração', verbose_name='Observações/Alertas')),
            ],
            options={
                'verbose_name': 'Escala',
                'verbose_name_plural': 'Escalas',
                'ordering': ['-ano', '-mes'],
                'unique_together': {('mes', 'ano')},
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome Completo')),
                ('data_nascimento', models.DateField(help_text='Necessário para calcular folga de aniversário', verbose_name='Data de Nascimento')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão')),
                ('tipo', models.CharField(choices=[('REGULAR', 'Regular'), ('FOLGUISTA', 'Folguista')], default='REGULAR', help_text='Regular trabalha na escala normal, Folguista entra apenas quando necessário', max_length=10, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='funcionarios', to='escala.turno', verbose_name='Turno Fixo')),
            ],
            options={
                'verbose_name': 'Funcionário',
                'verbose_name_plural': 'Funcionários',
                'ordering': ['turno', 'tipo', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='DiaEscala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data')),
                ('situacao', models.CharField(choices=[('TRABALHA', 'Trabalha'), ('FOLGA', 'Folga Regular'), ('FOLGA_ANIVERSARIO', 'Folga Aniversário'), ('FOLGA_FERIADO', 'Folga Compensatória Feriado')], max_length=20, verbose_name='Situação')),
                ('escala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dias', to='escala.escala', verbose_name='Escala')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dias_escala', to='escala.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'Dia da Escala',
                'verbose_name_plural': 'Dias da Escala',
                'ordering': ['data', 'funcionario'],
                'unique_together': {('escala', 'funcionario', 'data')},
            },
        ),
    ]
