# Generated by Django 5.0.6 on 2025-12-14 23:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoOcorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('categoria', models.CharField(choices=[('ACESSO', 'Controle de Acesso'), ('SUSPEITA', 'Presença Suspeita'), ('TENTATIVA', 'Tentativa de Ocorrência'), ('RONDA', 'Ronda'), ('ABORDAGEM', 'Abordagem'), ('TURNO', 'Turno / Plantão'), ('COMUNICACAO', 'Comunicação')], max_length=20)),
                ('gravidade', models.CharField(choices=[('INFO', 'Informativa'), ('ATENCAO', 'Atenção'), ('CRITICA', 'Crítica')], max_length=10)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['categoria', 'nome'],
            },
        ),
        migrations.AlterModelOptions(
            name='diaescala',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='escala',
            options={'ordering': ['-ano', '-mes']},
        ),
        migrations.AlterModelOptions(
            name='feriado',
            options={'ordering': ['data']},
        ),
        migrations.AlterModelOptions(
            name='funcionario',
            options={'ordering': ['nome']},
        ),
        migrations.AlterModelOptions(
            name='turno',
            options={'ordering': ['horario_entrada']},
        ),
        migrations.AlterField(
            model_name='diaescala',
            name='data',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diaescala',
            name='escala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='escala.escala'),
        ),
        migrations.AlterField(
            model_name='diaescala',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.funcionario'),
        ),
        migrations.AlterField(
            model_name='diaescala',
            name='situacao',
            field=models.CharField(choices=[('TRABALHA', 'Trabalha'), ('FOLGA', 'Folga')], max_length=20),
        ),
        migrations.AlterField(
            model_name='escala',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2024)]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='gerada_com_sucesso',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='escala',
            name='mes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='escala',
            name='observacoes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='data',
            field=models.DateField(unique=True),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='feriado',
            name='tipo',
            field=models.CharField(choices=[('NACIONAL', 'Nacional'), ('ESTADUAL', 'Estadual'), ('MUNICIPAL', 'Municipal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_admissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('FOLGUISTA', 'Folguista')], max_length=10),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='turno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.turno'),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario_entrada',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='horario_saida',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='turno',
            name='minimo_funcionarios',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='turno',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.TextField(blank=True)),
                ('acao_tomada', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.funcionario')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escala.tipoocorrencia')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
