# Generated by Django 4.2.24 on 2026-02-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0002_tipoocorrencia_alter_diaescala_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocorrencia',
            name='data_hora',
            field=models.DateTimeField(),
        ),
    ]
