# Generated by Django 4.2.24 on 2026-06-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0003_alter_ocorrencia_data_hora'),
        ('escala', '0004_turno_regime_funcionario_ferias_diaescala_situacao'),
    ]

    operations = [
    ]
