# Generated by Django 6.0.6 on 2026-06-28 03:27

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0010_grupo_folguista'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaescala',
            name='setor_coberto',
            field=models.ForeignKey(blank=True, help_text='Setor coberto pelo folguista neste dia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dias_cobertos', to='escala.grupo'),
        ),
        migrations.AddField(
            model_name='grupo',
            name='minimo_funcionarios',
            field=models.IntegerField(default=1, help_text='Mínimo de funcionários por dia neste setor', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='configuracaosistema',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='regime',
            field=models.CharField(choices=[('5x2', '5x2 — trabalha 5, folga 2 por semana'), ('6x1', '6x1 — trabalha 6, folga 1 por semana')], default='6x1', max_length=3),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='tipo',
            field=models.CharField(choices=[('REGULAR', 'Regular'), ('FOLGUISTA', 'Folguista')], default='REGULAR', max_length=10),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
