# Generated by Django 6.0.6 on 2026-06-28 03:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0011_add_setor_minimo_and_setor_coberto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grupo',
            name='minimo_funcionarios',
        ),
        migrations.CreateModel(
            name='SetorTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minimo_funcionarios', models.IntegerField(default=1, help_text='Mínimo de funcionários neste setor neste turno', validators=[django.core.validators.MinValueValidator(1)])),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turnos_operados', to='escala.grupo')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores_operados', to='escala.turno')),
            ],
            options={
                'verbose_name': 'Setor × Turno',
                'verbose_name_plural': 'Setores × Turnos',
                'ordering': ['setor__nome', 'turno__horario_entrada'],
                'unique_together': {('setor', 'turno')},
            },
        ),
    ]
