# Generated by Django 6.0.6 on 2026-06-28 16:52

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0014_perfilfuncionario_tokencadastrofuncionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ATRASO', 'Atraso'), ('ATESTADO', 'Atestado Médico'), ('OUTRO', 'Outro')], max_length=20)),
                ('descricao', models.TextField(blank=True)),
                ('arquivo', models.FileField(blank=True, null=True, upload_to='ocorrencias/')),
                ('data_ocorrencia', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('VISTO', 'Visto')], default='PENDENTE', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('observacao_gestor', models.TextField(blank=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='escala.funcionario')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
