# Generated by Django 6.0.6 on 2026-06-28 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0015_ocorrencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcessoFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('dispositivo', models.CharField(blank=True, max_length=20)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_acesso', to='escala.funcionario')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
    ]
