# Generated by Django 6.0.6 on 2026-06-28 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escala', '0016_log_acesso_funcionario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='ocorrencia',
            old_name='observacao_gestor',
            new_name='resposta',
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='visto_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ocorrencia',
            name='visto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ocorrencias_vistas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='ocorrencia',
            name='status',
            field=models.CharField(choices=[('PENDENTE', 'Pendente'), ('ANALISANDO', 'Analisando'), ('FINALIZADA', 'Finalizada')], default='PENDENTE', max_length=20),
        ),
    ]
